M: alacritty

window:
  padding:
    x: 2
    y: 2

  dynamic_padding: false

  title: Alacritty

  class:
    instance: Alacritty
    general: Alacritty

  gtk_theme_variant: None

scrolling:
  history: 10000
  multiplier: 1

font:
  normal:
    family: mono
    style: Medium
  size: 8
  offset:
    x: -1
    y: -1
  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: false
colors:
  primary:
    background: '#282828'
    foreground: '#d8dee9'

  cursor:
    text: '#191919'
    cursor: '#d8dee9'

  selection:
    text: '#191919'
    background: '#d8dee9'

  normal:
    black:   '#313539'
    red:     '#cc241d'
    green:   '#40a62f'
    yellow:  '#f2e635'
    blue:    '#458588'
    magenta: '#b30ad0'
    cyan:    '#32d0fc'
    white:   '#acadb1'

  bright:
    black:   '#313539'
    red:     '#b02626'
    green:   '#40a62f'
    yellow:  '#f2e635'
    blue:    '#314ad0'
    magenta: '#b30ad0'
    cyan:    '#32d0fc'
    white:   '#acadb1'

  dim:
    black:   '#676f78'
    red:     '#b55454'
    green:   '#78a670'
    yellow:  '#faf380'
    blue:    '#707fd0'
    magenta: '#c583d0'
    cyan:    '#8adaf1'
    white:   '#e0e3e7'

visual_bell:
  animation: EaseOutExpo
  duration: 0
  color: '#ffffff'

window:
  opacity: 0.8

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: false

dynamic_title: true

cursor:
  style: Underline
  unfocused_hollow: true

live_config_reload: true

working_directory: /home/morelly_t1/git

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hints:
    enabled:
      - regex: "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
        command: xdg-open
        post_processing: true
        mouse:
          enabled: true
          mods: Control
        binding:
          key: U
          mods: Control|Shift

mouse_bindings:
  - { mouse: Middle, action: Copy }

key_bindings:
  - { key: X,        mods: Control,       action: Paste            }
  - { key: Insert,   mods: Shift,         action: Paste            }
  - { key: Slash,    mods: Control,       chars: "gc"              }
  - { key: Y,        mods: Control,       action: Copy             }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize }
  - { key: NumpadSubtract, mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false

