" Settings "
set nocompatible              
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab  
set autowrite
set list lcs=tab:\|\ 

let g:go_highlight_types = 1
" Config "
filetype off                  
set rtp+=~/.vim/bundle/Vundle.vim

set number relativenumber
set cursorline
set cursorcolumn

" Save file as sudo when no sudo permissions
cnoremap w!! execute 'silent! write !sudo tee % >/dev/null' <bar> edit!

" Plugins "
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'JamshedVesuna/vim-markdown-preview'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'fatih/vim-go'
Plugin 'junegunn/fzf.vim'
Plugin 'iamcco/markdown-preview.nvim'
Plugin 'ObserverOfTime/coloresque.vim'
Plugin 'pearofducks/ansible-vim'
call vundle#end()
filetype plugin indent on

let g:airline_theme = 'base16_spacemacs'

" lf "
function! LF()
    let temp = tempname()
    exec 'silent !lf -selection-path=' . shellescape(temp)
    if !filereadable(temp)
        redraw!
        return
    endif
    let names = readfile(temp)
    if empty(names)
        redraw!
        return
    endif
    exec 'edit ' . fnameescape(names[0])
    for name in names[1:]
        exec 'argadd ' . fnameescape(name)
    endfor
    redraw!
endfunction
command! -bar LF call LF()

let vim_markdown_preview_toggle=1
let vim_markdown_preview_github=1
let vim_markdown_preview_use_xdg_open=1
