alias dot="cd ~/dotfiles"
alias gd="cd ~/git/"
alias gdf="cd ~/git/dotfiles"
alias ll="k"
alias l="k"
alias gitlab-runner="docker run --rm -v $PWD:$PWD -v /var/run/docker.sock:/var/run/docker.sock -v /opt/gitlab-runner/config:/etc/gitlab-runner --workdir $PWD gitlab/gitlab-runner"
alias s="sudo"
alias v="vim"
alias gam="git commit --amend --no-edit"

gq(){
  var=$(gossh) && ssh ${var}
}
