#! /bin/sh

kill $(pgrep sxhkd); sxhkd &
kill $(pgrep xcompmgr); xcompmgr &

# solo
[ $(xrandr -q | grep -w connected | wc -l) -eq 1 ] &&  {
	bspc monitor -d 1 2 3 4 5 6 7 8 9
	xrandr --output eDP-1 --mode 2560x1600 
}

# sva
[ $(xrandr -q | grep -w connected | cut -d " " -f1 | wc -l) = 3 ] && {
  xrandr --output eDP-1 --mode 2560x1600 --right-of DP-3-1
  xrandr --output DP-3-1 --auto --right-of DP-3-3
  #xrandr --output eDP-1 --mode 2560x1600 --right-of DP-3-2
  #xrandr --output DP-3-2 --auto --right-of DP-3-1
  bspc monitor DP-3-3 -d 1 2 3
  bspc monitor DP-3-1 -d 4 5 6
  #bspc monitor DP-3-1 -d 1 2 3
  #bspc monitor DP-3-2 -d 4 5 6
  bspc monitor eDP-1 -d 7 8 9
}

$HOME/.config/polybar/launch.sh

feh --bg-fill ~/git/dotfiles/config/wallpaper/wallpaper.jpg

bspc config border_width         2
bspc config window_gap          12
bspc config automatic_scheme alternate
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

###---Monitor And Desktop Settings----###
bspc config top_padding 24
bspc config bottom_padding 24
bspc config left_padding 4
bspc config right_padding 4
bspc config border_width 2
bspc config window_gap 10

#### Rules ###
bspc rule -a "PulseUI" state=floating
bspc rule -a "1Password" state=floating
bspc rule -a "Org.gnome.Nautilus"  state=floating
