#!/bin/sh

wmname LG3D & 
sxhkd &
xcompmgr &

$HOME/.config/polybar/launch.sh

# solo 
[ $(xrandr -q | grep -w connected | wc -l) -eq 1 ] &&  {
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
}

# sva
[ $(xrandr -q | grep -w connected | wc -l) -eq 2 ] &&  {
  bspc monitor eDP-1 -d 1 2 3 4 
  bspc monitor HDMI-1 -d 5 6 7 8 
}

# home office 
[ $(xrandr -q | grep -w connected | wc -l) -eq 3 ] &&  {
 # bash ~/git/dotfiles/scripts/connect_screens.sh home
  bspc monitor eDP-1 -d 1 2 3
  bspc monitor DVI-I-2-2 -d 4 5 6
  bspc monitor DVI-I-1-1 -d 7 8 9
}

bspc config border_width         2
bspc config window_gap          12
bspc config automatic_scheme longest_side
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

###---Monitor And Desktop Settings----###
bspc config top_padding 32
bspc config bottom_padding 10
bspc config left_padding 10
bspc config right_padding 10
bspc config border_width 2
bspc config window_gap 10

# background
feh --bg-fill ~/.config/bspwm/wallpaper.jpg

# rules
bspc rule -a Spotify desktop=^1
bspc rule -a Firefox desktop=^7

bspc rule -a Teams desktop=^8 state=tiled
bspc rule -a Slack desktop=^8 state=tiled

bspc rule -a PulseUi state=floating
bspc rule -a tetris state=floating
bspc rule -a Code desktop=^4 state=tiled
