#!/bin/sh

bspc rule -r "*"
wmname LG3D & 
sxhkd &
xcompmgr &

# solo 
[ $(xrandr -q | grep -w connected | wc -l) -eq 1 ] &&  {
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
}

# sva
[ $(xrandr -q | grep -w connected | cut -d " " -f1 | wc -l) = 3 ] && {
  bspc monitor DP-2-1 -d 1 2 3
  bspc monitor DP-2-2 -d 4 5 6
  bspc monitor eDP-1 -d 7 8 9 
  xrandr --output DP-2-2 --auto --right-of DP-2-1 --output eDP-1 --auto --right-of DP-2-2
}

 home office
[ $(xrandr -q | grep -w connected | cut -d " " -f1 | wc -l) = 2 ] && {
  bspc monitor eDP-1 -d 1 2 3 4
  bspc monitor DVI-I-1-1 -d 5 6 7 8
  #bspc monitor DVI-I-2-2 -d 7 8 9
  #xrandr --output DVI-I-1-1 --auto --right-of eDP-1 --output DVI-I-2-2 --auto --right-of DVI-I-1-1
  xrandr --output DVI-I-1-1 --auto --right-of eDP-1 
}

$HOME/.config/polybar/launch.sh

bspc config border_width         2
bspc config window_gap          12
bspc config automatic_scheme alternate
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

###---Monitor And Desktop Settings----###
bspc config top_padding 32
bspc config bottom_padding 10
bspc config left_padding 10
bspc config right_padding 10
bspc config border_width 2
bspc config window_gap 10

# random background for all screens 
WALL=$(find "${HOME}/Pictures/wallpaper/" -type f | sort -R | tail -1)
wal -n -i $WALL 
feh --randomize --bg-fill "$WALL"

# rules
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a marktext state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Spotify desktop=^1
bspc rule -a Firefox desktop=^7
bspc rule -a PulseUi state=floating
bspc rule -a Tetris state=floating
bspc rule -a Code desktop=^4 state=tiled
bspc rule -a Pavucontrol state=floating
bspc rule -a Slack desktop=^9 state=tiled
bspc rule -a "whatsapp-nativefier-d40211" desktop=^8 state=tiled
bspc rule -a "Microsoft Teams - Preview" desktop=^8 state=tiled
bspc rule -a "mail-nativefier-2a283a" desktop=^8 state=tiled
