export TERM=xterm-256color
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export VISUAL=vim
export EDITOR=$VISUAL
export AUTO_LS_COMMANDS=(custom_function)

# source ~/.bash_profile
auto-ls-custom_function () {
  echo "$PWD"
  exa -l
  [[ -d ".git" ]] && echo -e "\nStatus:\n$(git -c color.status=always status -s)"
}

export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin:${HOME}/.local.bin/:$HOME/git/github/dotfiles/scripts:$HOME/.tfenv/bin

# ------------------------------- ZSH SETTINGS --------------------------------
# ----- options -----
unsetopt NO_BEEP
unsetopt NO_MATCH
setopt globdots
setopt AUTO_CD
setopt BEEP
setopt NOMATCH
setopt NOTIFY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt HIST_BEEP
setopt INTERACTIVE_COMMENTS
setopt MAGIC_EQUAL_SUBST

HISTFILE="$HOME/.zsh_history"
HIST_STAMPS=mm/dd/yyyy
DISABLE_UPDATE_PROMPT=true
HISTSIZE=5000
SAVEHIST=5000
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#ccc'
ZLE_RPROMPT_INDENT=0

# ----- keys -----
bindkey '^[[2~' overwrite-mode
bindkey '^[[3~' delete-char
bindkey '^[[H' beginning-of-line
bindkey '^[[1~' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^[[4~' end-of-line
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^[[3;5~' kill-word
bindkey '^i' expand-or-complete-prefix

# ----- promt -----
PS1="%F{cyan} %~ >%F{blue}> %F{reset}"

# ----- plugins -----
source ~/antigen.zsh
source ~/.oh-my-zsh/custom/plugins/git-flow-completion/git-flow-completion.zsh
source ~/.oh-my-zsh/custom/plugins/git/git.plugin.zsh

antigen use oh-my-zsh
antigen bundle gko/ssh-connect
antigen bundle akarzim/zsh-docker-aliases
antigen bundle djui/alias-tips
antigen bundle trystan2k/zsh-tab-title
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle colored-man-pages
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle desyncr/auto-ls
antigen theme denysdovhan/spaceship-prompt
antigen apply

[[ -s /home/$USER/.autojump/etc/profile.d/autojump.sh ]] && source /home/$USER/.autojump/etc/profile.d/autojump.sh
autoload compinit && compinit

# - Spaceship 
SPACESHIP_PROMPT_ORDER=(
  user
  host
  dir
  git
  golang
  terraform
  exec_time
  exit_code
  char
)

SPACESHIP_USER_SHOW="always"
SPACESHIP_HOST_SHOW="always"
SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=true
SPACESHIP_GIT_LAST_COMMIT_SHOW=true
SPACESHIP_PROMPT_ADD_NEWLINE=true
SPACESHIP_CHAR_SYMBOL=❯
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_EXIT_CODE_SHOW=true

# Spaceship Prompt
autoload -U promptinit; promptinit
prompt spaceship

# direnv
eval "$(direnv hook zsh)"

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit

# GoLang
export PATH=$GOROOT/bin:$PATH
export GOPATH=/home/morelly_t1/go
source /home/morelly_t1/.gvm/scripts/gvm